name: CI ReservApp

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  compile:
    name: Compilar Proyecto
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.4.5
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: reservapp
          MYSQL_USER: reservapp
          MYSQL_PASSWORD: reservapp
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: 'maven'
          cache-dependency-path: './ReservApp/pom.xml'
      - name: Compilar con Maven
        run: cd ReservApp && mvn clean install

  test:
    name: Ejecutar Tests
    runs-on: ubuntu-latest
    needs: compile
    services:
      mysql:
        image: mysql:8.4.5
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: reservapp
          MYSQL_USER: reservapp
          MYSQL_PASSWORD: reservapp
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: 'maven'
          cache-dependency-path: './ReservApp/pom.xml'
      - name: Ejecutar Tests Maven
        run: cd ReservApp && mvn test

  sonarqube:
    name: Análisis SonarQube
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: 'maven'
          cache-dependency-path: './ReservApp/pom.xml'
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ReservApp -Dsonar.branch.name=main
        working-directory: ./ReservApp
