spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

---
# Configuración de desarrollo
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    es.ubu.reservapp: DEBUG
    org.springframework.web: DEBUG

---
# Configuración de producción
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
logging:
  level:
    root: WARN
    es.ubu.reservapp: INFO